name: Style PHP-CS-Fixer

on:
  push:
    branches: [ 1.x ]
  pull_request:
    branches: [ 1.x ]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install composer packages
        run: composer install

      - name: Run PHP-CS-Fixer Style
        run: ./vendor/bin/php-cs-fixer fix

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.6

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply PHP-CS-Fixer changes
